version: "3.4"

volumes:
    db_data:
    php_socket:

services:
    php:
        build:
            context: ./docker/php/
        working_dir: /srv/
        volumes:
            - "./backend/:/srv"
            - "php_socket:/var/run/php"

    caddy:
        build:
            context: ./docker/caddy/
        working_dir: /srv/
        volumes:
            - "php_socket:/var/run/php"
            - "./backend/:/srv/"
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"

    mailcatcher:
        build: ./docker/mailcatcher/

    node:
        build: ./docker/node/
        working_dir: /srv/
        ports:
            - "3000:3000"
        volumes:
            - "./frontend/:/srv"

    database:
        image: "postgres:14-alpine"
        working_dir: /srv/
        volumes: ["db_data:/var/lib/postgresql/data"]
        environment:
            POSTGRES_PASSWORD: app
            POSTGRES_USER: app
